### ISSUE TITLE
 Convert Drosophila motoneuron model to NeuroML2

### ISSUE THREAD

**Issue by pgleeson** [cengique/drosophila-aCC-L3-motoneuron-model#2]
See https://github.com/OpenSourceBrain/Contribute/issues/1

@cengique, this has been added to a central repository for OSB project suggestions/ideas/help requests. Hopefully someone will jump on board & help convert it to NeuroML2...

**Comment by jrieke** [comment]
Will work on this. Closing to split it into more detailed issues.
