### ISSUE TITLE
Add OMV tests for comparing spike times to XPP version

### ISSUE THREAD

**Issue by pgleeson** [cengique/drosophila-aCC-L3-motoneuron-model#5]
Use Pinsky Rinzel example as basis for this, see:
https://github.com/OpenSourceBrain/PinskyRinzelModel/blob/master/NeuroML2/LEMS/.test.fig3.jnml.omt
https://github.com/OpenSourceBrain/PinskyRinzelModel/blob/master/NeuroML2/LEMS/.test.fig3.mep
https://github.com/OpenSourceBrain/PinskyRinzelModel/blob/master/.travis.yml

Either modify XPP script to save spike times or record to file the trace via XPP interface and work them out.

**Comment by borismarin** [comment]
@jrieke Contributions to `omv`  itself are also welcome! https://github.com/OpenSourceBrain/osb-model-validation

**Comment by cengique** [comment]
@borismarin OMV looks great! We do need continuous integration in comp neurosci!

**Comment by borismarin** [comment]
@cengique thanks! it would be lovely to have more sophisticated metric for
comparing activity though - I wonder if we could open your Pandora box and
reuse some of the functionality...

**Comment by jrieke** [comment]
@cengique Could you please enable Travis CI for this repository (see first two steps [here](http://docs.travis-ci.com/user/getting-started/), I will take care of everything else), so we can run automated tests?

**Comment by cengique** [comment]
@borismarin you're right I have all kinds of scripts that are made for these data. They are already all included in the ModelDB page for this model and paper.

**Comment by cengique** [comment]
@jrieke I started the Travis CI registration, but somehow it's making me wait forever. I'll try to get back to it later.

**Comment by cengique** [comment]
@jrieke I have now enabled Travis CI for this repo.

**Comment by jrieke** [comment]
@cengique Great, thanks! I added all tests, and also added a travis build badge to the readme file (it's currently failing because the pure NeuroML2 version is not finished yet).

**Comment by pgleeson** [comment]
How were the times in [here](https://github.com/cengique/drosophila-aCC-L3-motoneuron-model/blob/master/NeuroML2/.isopotential.mep) calculated? How close are they to the original XPP version?

**Comment by jrieke** [comment]
I used the results from [isopotential_LEMS.xml](https://github.com/cengique/drosophila-aCC-L3-motoneuron-model/blob/master/NeuroML2/isopotential_LEMS.xml) but checked for all values that they fit with the output from the XPP version (which they do completely, i. e. the change from < -25mV to > -25mV occurs at exactly the same time step).
