### ISSUE TITLE
isopotential.ode dynamics

### ISSUE THREAD

**Issue by borismarin** [cengique/drosophila-aCC-L3-motoneuron-model#6]
Some points tbd
- the xpp implementation is not settling into a stable equilibrium (i.e. resting potential) for low I clamps - this is due to the fact that hkf2 diverges (steps to reproduce: increase total integration time and watch hkf2 grow for the default Ihold=-12)
- the initial condition for hkf2 is > 1 (and 5 < hkf2 < 7 for a clamp-induced burst). 
- That's probably the reason behind [this comment](https://github.com/cengique/drosophila-aCC-L3-motoneuron-model/blob/master/xpp-models/isopotential.ode#L36) in the sources.
- making `dhKf2/dt=(hinfK2(V)-hKf)/116` into `dhKf2/dt=(hinfK2(V)-hKf2)/116` (hkf->hkf2) potentially solves the problem, but it would be important to understand this specific current better.

**Comment by cengique** [comment]
@borismarin I think that's just a typo in the code. And your suggested solution is correct. As _Ikf_ did not play an important role in the firing behaviors we were studying, I must have not realized this bug. I just committed your solution. Thanks and let me know if you find some more interesting behaviors in _Ikf_!

**Comment by jrieke** [comment]
@cengique I just came here to ask you the exact same thing :) I looked at the two-compartmental model a few hours ago and saw that it uses the correct equation (with hKf2 instead of hKf), so I already thought that it may be a typo. Anyway, thanks for fixing this!

**Comment by jrieke** [comment]
Adjusted the behaviour of the LEMS and NeuroML models to the corrected hKf2 channel; everything should work now.

**Comment by cengique** [comment]
@jrieke: It makes sense that the 2-compartment model has this fixed! I didn't think of looking there. The isopotential model  was the first trial, and things evolved after that. So apparently I forgot to fix a few things that required going back to the older model versions. :/

**Comment by jrieke** [comment]
@cengique How did you actually come up with the hKf2 variable? I found a short sentence about it in the paper where you published the model previously ([Lin et. al. 2012](http://www.jneurosci.org/content/32/21/7267), below table 2), but nothing else in the literature or your paper. What was your motivation or objective behind including this?

**Comment by cengique** [comment]
@jrieke: It's based on the data and fits. There are other labs who fit two time constants to the fast inactivating current. It's still an approximation to the complex Markov models that can more accurately describe channel states. I was supposed to write another paper focusing on the data fits, but it fell through the cracks. But in summary, the hkf2 only contributes 5% of the current magnitude, so it could easily be left out without a big loss. Let me know if I didn't answer your question completely.
